export const BPMN_ELEMENTS = {
    XOR: "exclusiveGateway",
    OR: "inclusiveGateway",
    AND: "parallelGateway",
    EVENT_BASED: "eventBasedGateway",
    TASK: "task",
    SCRIPT_TASK: "scriptTask",
    BUSINESS_RULE_TASK: "businessRuleTask",
    SERVICE_TASK: "serviceTask",
    USER_TASK: "userTask",
    SEQUENCE_FLOW: "sequenceFlow",
    MESSAGE_FLOW: "messageFlow",
    MANUAL_TASK: "manualTask",
    POOL: "participant",
    DATA_OBJECT: "dataObject",
};
